/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDataHealthRouteImport } from './routes/_authenticated/data-health'
import { Route as AuthenticatedFlashRouteImport } from './routes/_authenticated/flash'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedOccupancyRouteImport } from './routes/_authenticated/occupancy'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin/access'
import { Route as AuthenticatedAdminCommunitiesRouteImport } from './routes/_authenticated/admin/communities'
import { Route as AuthenticatedAdminDataSourcesRouteImport } from './routes/_authenticated/admin/data-sources'
import { Route as AuthenticatedAdminGoalsRouteImport } from './routes/_authenticated/admin/goals'
import { Route as AuthenticatedAdminGscImportsRouteImport } from './routes/_authenticated/admin/gsc-imports'
import { Route as AuthenticatedAdminMappingsRouteImport } from './routes/_authenticated/admin/mappings'
import { Route as AuthenticatedAdminMetricsRouteImport } from './routes/_authenticated/admin/metrics'
import { Route as AuthenticatedAdminOccupancyHistoryRouteImport } from './routes/_authenticated/admin/occupancy-history'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin/organizations'
import { Route as AuthenticatedAdminQueryRulesRouteImport } from './routes/_authenticated/admin/query-rules'
import { Route as AuthenticatedAdminUrlRulesRouteImport } from './routes/_authenticated/admin/url-rules'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin/validation'
import { Route as AuthenticatedAdminWelcomehomeRouteImport } from './routes/_authenticated/admin/welcomehome'
import { Route as AuthenticatedAdminWhMappingsRouteImport } from './routes/_authenticated/admin/wh-mappings'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated/marketing/index'
import { Route as AuthenticatedMarketingOpportunitiesRouteImport } from './routes/_authenticated/marketing/opportunities'
import { Route as AuthenticatedMarketingPagesRouteImport } from './routes/_authenticated/marketing/pages'
import { Route as AuthenticatedMarketingQueriesRouteImport } from './routes/_authenticated/marketing/queries'
import { Route as AuthenticatedMarketingSegmentsRouteImport } from './routes/_authenticated/marketing/segments'
import { Route as ApiPublicHooksWhNightlyRouteImport } from './routes/api/public/hooks/wh-nightly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataHealthRoute = AuthenticatedDataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlashRoute = AuthenticatedFlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOccupancyRoute = AuthenticatedOccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommunitiesRoute =
  AuthenticatedAdminCommunitiesRouteImport.update({
    id: '/admin/communities',
    path: '/admin/communities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDataSourcesRoute =
  AuthenticatedAdminDataSourcesRouteImport.update({
    id: '/admin/data-sources',
    path: '/admin/data-sources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGoalsRoute = AuthenticatedAdminGoalsRouteImport.update({
  id: '/admin/goals',
  path: '/admin/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGscImportsRoute =
  AuthenticatedAdminGscImportsRouteImport.update({
    id: '/admin/gsc-imports',
    path: '/admin/gsc-imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMappingsRoute =
  AuthenticatedAdminMappingsRouteImport.update({
    id: '/admin/mappings',
    path: '/admin/mappings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMetricsRoute =
  AuthenticatedAdminMetricsRouteImport.update({
    id: '/admin/metrics',
    path: '/admin/metrics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOccupancyHistoryRoute =
  AuthenticatedAdminOccupancyHistoryRouteImport.update({
    id: '/admin/occupancy-history',
    path: '/admin/occupancy-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQueryRulesRoute =
  AuthenticatedAdminQueryRulesRouteImport.update({
    id: '/admin/query-rules',
    path: '/admin/query-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUrlRulesRoute =
  AuthenticatedAdminUrlRulesRouteImport.update({
    id: '/admin/url-rules',
    path: '/admin/url-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/admin/validation',
    path: '/admin/validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWelcomehomeRoute =
  AuthenticatedAdminWelcomehomeRouteImport.update({
    id: '/admin/welcomehome',
    path: '/admin/welcomehome',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWhMappingsRoute =
  AuthenticatedAdminWhMappingsRouteImport.update({
    id: '/admin/wh-mappings',
    path: '/admin/wh-mappings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingOpportunitiesRoute =
  AuthenticatedMarketingOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingPagesRoute =
  AuthenticatedMarketingPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingQueriesRoute =
  AuthenticatedMarketingQueriesRouteImport.update({
    id: '/queries',
    path: '/queries',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedMarketingSegmentsRoute =
  AuthenticatedMarketingSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const ApiPublicHooksWhNightlyRoute = ApiPublicHooksWhNightlyRouteImport.update({
  id: '/api/public/hooks/wh-nightly',
  path: '/api/public/hooks/wh-nightly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/flash': typeof AuthenticatedFlashRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/occupancy': typeof AuthenticatedOccupancyRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/communities': typeof AuthenticatedAdminCommunitiesRoute
  '/admin/data-sources': typeof AuthenticatedAdminDataSourcesRoute
  '/admin/goals': typeof AuthenticatedAdminGoalsRoute
  '/admin/gsc-imports': typeof AuthenticatedAdminGscImportsRoute
  '/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/admin/occupancy-history': typeof AuthenticatedAdminOccupancyHistoryRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/query-rules': typeof AuthenticatedAdminQueryRulesRoute
  '/admin/url-rules': typeof AuthenticatedAdminUrlRulesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/admin/welcomehome': typeof AuthenticatedAdminWelcomehomeRoute
  '/admin/wh-mappings': typeof AuthenticatedAdminWhMappingsRoute
  '/marketing/opportunities': typeof AuthenticatedMarketingOpportunitiesRoute
  '/marketing/pages': typeof AuthenticatedMarketingPagesRoute
  '/marketing/queries': typeof AuthenticatedMarketingQueriesRoute
  '/marketing/segments': typeof AuthenticatedMarketingSegmentsRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/api/public/hooks/wh-nightly': typeof ApiPublicHooksWhNightlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-health': typeof AuthenticatedDataHealthRoute
  '/flash': typeof AuthenticatedFlashRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/occupancy': typeof AuthenticatedOccupancyRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/communities': typeof AuthenticatedAdminCommunitiesRoute
  '/admin/data-sources': typeof AuthenticatedAdminDataSourcesRoute
  '/admin/goals': typeof AuthenticatedAdminGoalsRoute
  '/admin/gsc-imports': typeof AuthenticatedAdminGscImportsRoute
  '/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/admin/occupancy-history': typeof AuthenticatedAdminOccupancyHistoryRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/query-rules': typeof AuthenticatedAdminQueryRulesRoute
  '/admin/url-rules': typeof AuthenticatedAdminUrlRulesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/admin/welcomehome': typeof AuthenticatedAdminWelcomehomeRoute
  '/admin/wh-mappings': typeof AuthenticatedAdminWhMappingsRoute
  '/marketing/opportunities': typeof AuthenticatedMarketingOpportunitiesRoute
  '/marketing/pages': typeof AuthenticatedMarketingPagesRoute
  '/marketing/queries': typeof AuthenticatedMarketingQueriesRoute
  '/marketing/segments': typeof AuthenticatedMarketingSegmentsRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/api/public/hooks/wh-nightly': typeof ApiPublicHooksWhNightlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/data-health': typeof AuthenticatedDataHealthRoute
  '/_authenticated/flash': typeof AuthenticatedFlashRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/occupancy': typeof AuthenticatedOccupancyRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/communities': typeof AuthenticatedAdminCommunitiesRoute
  '/_authenticated/admin/data-sources': typeof AuthenticatedAdminDataSourcesRoute
  '/_authenticated/admin/goals': typeof AuthenticatedAdminGoalsRoute
  '/_authenticated/admin/gsc-imports': typeof AuthenticatedAdminGscImportsRoute
  '/_authenticated/admin/mappings': typeof AuthenticatedAdminMappingsRoute
  '/_authenticated/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/_authenticated/admin/occupancy-history': typeof AuthenticatedAdminOccupancyHistoryRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/query-rules': typeof AuthenticatedAdminQueryRulesRoute
  '/_authenticated/admin/url-rules': typeof AuthenticatedAdminUrlRulesRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/admin/welcomehome': typeof AuthenticatedAdminWelcomehomeRoute
  '/_authenticated/admin/wh-mappings': typeof AuthenticatedAdminWhMappingsRoute
  '/_authenticated/marketing/opportunities': typeof AuthenticatedMarketingOpportunitiesRoute
  '/_authenticated/marketing/pages': typeof AuthenticatedMarketingPagesRoute
  '/_authenticated/marketing/queries': typeof AuthenticatedMarketingQueriesRoute
  '/_authenticated/marketing/segments': typeof AuthenticatedMarketingSegmentsRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/api/public/hooks/wh-nightly': typeof ApiPublicHooksWhNightlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-health'
    | '/flash'
    | '/forecast'
    | '/journey'
    | '/marketing'
    | '/occupancy'
    | '/overview'
    | '/sales'
    | '/admin/access'
    | '/admin/communities'
    | '/admin/data-sources'
    | '/admin/goals'
    | '/admin/gsc-imports'
    | '/admin/mappings'
    | '/admin/metrics'
    | '/admin/occupancy-history'
    | '/admin/organizations'
    | '/admin/query-rules'
    | '/admin/url-rules'
    | '/admin/validation'
    | '/admin/welcomehome'
    | '/admin/wh-mappings'
    | '/marketing/opportunities'
    | '/marketing/pages'
    | '/marketing/queries'
    | '/marketing/segments'
    | '/marketing/'
    | '/api/public/hooks/wh-nightly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-health'
    | '/flash'
    | '/forecast'
    | '/journey'
    | '/occupancy'
    | '/overview'
    | '/sales'
    | '/admin/access'
    | '/admin/communities'
    | '/admin/data-sources'
    | '/admin/goals'
    | '/admin/gsc-imports'
    | '/admin/mappings'
    | '/admin/metrics'
    | '/admin/occupancy-history'
    | '/admin/organizations'
    | '/admin/query-rules'
    | '/admin/url-rules'
    | '/admin/validation'
    | '/admin/welcomehome'
    | '/admin/wh-mappings'
    | '/marketing/opportunities'
    | '/marketing/pages'
    | '/marketing/queries'
    | '/marketing/segments'
    | '/marketing'
    | '/api/public/hooks/wh-nightly'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/data-health'
    | '/_authenticated/flash'
    | '/_authenticated/forecast'
    | '/_authenticated/journey'
    | '/_authenticated/marketing'
    | '/_authenticated/occupancy'
    | '/_authenticated/overview'
    | '/_authenticated/sales'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/communities'
    | '/_authenticated/admin/data-sources'
    | '/_authenticated/admin/goals'
    | '/_authenticated/admin/gsc-imports'
    | '/_authenticated/admin/mappings'
    | '/_authenticated/admin/metrics'
    | '/_authenticated/admin/occupancy-history'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/query-rules'
    | '/_authenticated/admin/url-rules'
    | '/_authenticated/admin/validation'
    | '/_authenticated/admin/welcomehome'
    | '/_authenticated/admin/wh-mappings'
    | '/_authenticated/marketing/opportunities'
    | '/_authenticated/marketing/pages'
    | '/_authenticated/marketing/queries'
    | '/_authenticated/marketing/segments'
    | '/_authenticated/marketing/'
    | '/api/public/hooks/wh-nightly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksWhNightlyRoute: typeof ApiPublicHooksWhNightlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data-health': {
      id: '/_authenticated/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof AuthenticatedDataHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flash': {
      id: '/_authenticated/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof AuthenticatedFlashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/occupancy': {
      id: '/_authenticated/occupancy'
      path: '/occupancy'
      fullPath: '/occupancy'
      preLoaderRoute: typeof AuthenticatedOccupancyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/communities': {
      id: '/_authenticated/admin/communities'
      path: '/admin/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AuthenticatedAdminCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/data-sources': {
      id: '/_authenticated/admin/data-sources'
      path: '/admin/data-sources'
      fullPath: '/admin/data-sources'
      preLoaderRoute: typeof AuthenticatedAdminDataSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/goals': {
      id: '/_authenticated/admin/goals'
      path: '/admin/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AuthenticatedAdminGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gsc-imports': {
      id: '/_authenticated/admin/gsc-imports'
      path: '/admin/gsc-imports'
      fullPath: '/admin/gsc-imports'
      preLoaderRoute: typeof AuthenticatedAdminGscImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mappings': {
      id: '/_authenticated/admin/mappings'
      path: '/admin/mappings'
      fullPath: '/admin/mappings'
      preLoaderRoute: typeof AuthenticatedAdminMappingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/metrics': {
      id: '/_authenticated/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AuthenticatedAdminMetricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/occupancy-history': {
      id: '/_authenticated/admin/occupancy-history'
      path: '/admin/occupancy-history'
      fullPath: '/admin/occupancy-history'
      preLoaderRoute: typeof AuthenticatedAdminOccupancyHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/query-rules': {
      id: '/_authenticated/admin/query-rules'
      path: '/admin/query-rules'
      fullPath: '/admin/query-rules'
      preLoaderRoute: typeof AuthenticatedAdminQueryRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/url-rules': {
      id: '/_authenticated/admin/url-rules'
      path: '/admin/url-rules'
      fullPath: '/admin/url-rules'
      preLoaderRoute: typeof AuthenticatedAdminUrlRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/admin/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/welcomehome': {
      id: '/_authenticated/admin/welcomehome'
      path: '/admin/welcomehome'
      fullPath: '/admin/welcomehome'
      preLoaderRoute: typeof AuthenticatedAdminWelcomehomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/wh-mappings': {
      id: '/_authenticated/admin/wh-mappings'
      path: '/admin/wh-mappings'
      fullPath: '/admin/wh-mappings'
      preLoaderRoute: typeof AuthenticatedAdminWhMappingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/opportunities': {
      id: '/_authenticated/marketing/opportunities'
      path: '/opportunities'
      fullPath: '/marketing/opportunities'
      preLoaderRoute: typeof AuthenticatedMarketingOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/pages': {
      id: '/_authenticated/marketing/pages'
      path: '/pages'
      fullPath: '/marketing/pages'
      preLoaderRoute: typeof AuthenticatedMarketingPagesRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/queries': {
      id: '/_authenticated/marketing/queries'
      path: '/queries'
      fullPath: '/marketing/queries'
      preLoaderRoute: typeof AuthenticatedMarketingQueriesRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/marketing/segments': {
      id: '/_authenticated/marketing/segments'
      path: '/segments'
      fullPath: '/marketing/segments'
      preLoaderRoute: typeof AuthenticatedMarketingSegmentsRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/api/public/hooks/wh-nightly': {
      id: '/api/public/hooks/wh-nightly'
      path: '/api/public/hooks/wh-nightly'
      fullPath: '/api/public/hooks/wh-nightly'
      preLoaderRoute: typeof ApiPublicHooksWhNightlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingOpportunitiesRoute: typeof AuthenticatedMarketingOpportunitiesRoute
  AuthenticatedMarketingPagesRoute: typeof AuthenticatedMarketingPagesRoute
  AuthenticatedMarketingQueriesRoute: typeof AuthenticatedMarketingQueriesRoute
  AuthenticatedMarketingSegmentsRoute: typeof AuthenticatedMarketingSegmentsRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingOpportunitiesRoute:
      AuthenticatedMarketingOpportunitiesRoute,
    AuthenticatedMarketingPagesRoute: AuthenticatedMarketingPagesRoute,
    AuthenticatedMarketingQueriesRoute: AuthenticatedMarketingQueriesRoute,
    AuthenticatedMarketingSegmentsRoute: AuthenticatedMarketingSegmentsRoute,
    AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDataHealthRoute: typeof AuthenticatedDataHealthRoute
  AuthenticatedFlashRoute: typeof AuthenticatedFlashRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedOccupancyRoute: typeof AuthenticatedOccupancyRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminCommunitiesRoute: typeof AuthenticatedAdminCommunitiesRoute
  AuthenticatedAdminDataSourcesRoute: typeof AuthenticatedAdminDataSourcesRoute
  AuthenticatedAdminGoalsRoute: typeof AuthenticatedAdminGoalsRoute
  AuthenticatedAdminGscImportsRoute: typeof AuthenticatedAdminGscImportsRoute
  AuthenticatedAdminMappingsRoute: typeof AuthenticatedAdminMappingsRoute
  AuthenticatedAdminMetricsRoute: typeof AuthenticatedAdminMetricsRoute
  AuthenticatedAdminOccupancyHistoryRoute: typeof AuthenticatedAdminOccupancyHistoryRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminQueryRulesRoute: typeof AuthenticatedAdminQueryRulesRoute
  AuthenticatedAdminUrlRulesRoute: typeof AuthenticatedAdminUrlRulesRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
  AuthenticatedAdminWelcomehomeRoute: typeof AuthenticatedAdminWelcomehomeRoute
  AuthenticatedAdminWhMappingsRoute: typeof AuthenticatedAdminWhMappingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDataHealthRoute: AuthenticatedDataHealthRoute,
  AuthenticatedFlashRoute: AuthenticatedFlashRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedOccupancyRoute: AuthenticatedOccupancyRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminCommunitiesRoute: AuthenticatedAdminCommunitiesRoute,
  AuthenticatedAdminDataSourcesRoute: AuthenticatedAdminDataSourcesRoute,
  AuthenticatedAdminGoalsRoute: AuthenticatedAdminGoalsRoute,
  AuthenticatedAdminGscImportsRoute: AuthenticatedAdminGscImportsRoute,
  AuthenticatedAdminMappingsRoute: AuthenticatedAdminMappingsRoute,
  AuthenticatedAdminMetricsRoute: AuthenticatedAdminMetricsRoute,
  AuthenticatedAdminOccupancyHistoryRoute:
    AuthenticatedAdminOccupancyHistoryRoute,
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminQueryRulesRoute: AuthenticatedAdminQueryRulesRoute,
  AuthenticatedAdminUrlRulesRoute: AuthenticatedAdminUrlRulesRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
  AuthenticatedAdminWelcomehomeRoute: AuthenticatedAdminWelcomehomeRoute,
  AuthenticatedAdminWhMappingsRoute: AuthenticatedAdminWhMappingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksWhNightlyRoute: ApiPublicHooksWhNightlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
